"""Fit the learning-rate scaling of each arm and predict its 500M learning rate (research/LR_SCALING.md).

Per width: lr* is the vertex of the parabola in log2(lr) through the best grid
point and its two neighbours, kept within one grid step of the best point;
when a neighbour diverged, lr* is the best grid point. Per arm:
log2 lr* = a + b log2 N (N = non-embedding parameters), least squares over the
three widths. The training-length exponent c (change in log2 lr* per doubling
of tokens) is measured at the smallest width of the Transformer and of the
compute-aware arms; each heavy arm uses the compute-aware arm of its family.
Prediction for a 500M run of S steps: a + b log2 N_500 + c log2(S / sweep steps).
A shared-slope fit (one b, per-arm a) is reported as a robustness check.
"""
import json,math
from pathlib import Path
import numpy as np
from scripts.lr_sweep import LADDER,HORIZON_ARMS,RESULTS,RUNS,grid,lr_of,outcome,plan,run_name

# Non-embedding parameters of the 500M arms (run.json of the two-GPU throughput runs; PROFILE.md).
N_500={'transformer':475_915_520,'rdt_aware':479_253_760,'ctm_aware':440_982_784,'rdt_heavy':520_337_664,'ctm_heavy':446_064_128}
TARGETS={'transformer_1b':('transformer',1e9),'transformer_2b':('transformer',2e9),'rdt_aware':('rdt_aware',2e9),
         'ctm_aware':('ctm_aware',2e9),'rdt_heavy':('rdt_heavy',1e9),'ctm_heavy':('ctm_heavy',1e9)}
HORIZON_SOURCE={'transformer':'transformer','rdt_aware':'rdt_aware','rdt_heavy':'rdt_aware','ctm_aware':'ctm_aware','ctm_heavy':'ctm_aware'}
TOKENS_PER_STEP=1024*256


def vertex(losses,best):
    """log2 lr* (in grid units k) from the losses {k: loss} around the best k."""
    l,m,r=(losses.get(best+i,math.inf) for i in (-1,0,1))
    if not (math.isfinite(l) and math.isfinite(r)):return float(best)
    curvature=l-2*m+r
    return float(best) if curvature<=0 else best+max(-1.0,min(1.0,0.5*(l-r)/curvature))


def width_result(arm,d,h):
    ks=sorted(k for (a,dd,k,hh,seed) in plan()[0] if (a,dd,hh)==(arm,d,h))
    if not ks:return None
    ks,best,_=grid(arm,d,h,ks)
    if best is None:return None  # unfinished or unresolved
    losses={k:outcome(run_name(arm,d,k,h))[1] for k in ks}
    info=json.loads((RUNS/run_name(arm,d,best,h)/'run.json').read_text())
    star=vertex(losses,best)
    return {'arm':arm,'d_model':d,'horizon':h,'non_embedding_parameters':info['non_embedding_parameters'],'steps':info['run']['train']['total_steps'],
            'losses':{f'{lr_of(k):.3g}':(v if math.isfinite(v) else None) for k,v in losses.items()},'best_lr':lr_of(best),'k_star':star,'lr_star':lr_of(star)}


def main():
    widths=[w for arm in LADDER for d in LADDER[arm] for h in (1,4) if (w:=width_result(arm,d,h))]
    fits={}
    for arm in LADDER:
        pts=[w for w in widths if w['arm']==arm and w['horizon']==1]
        if len(pts)<2:continue
        x=np.log2([w['non_embedding_parameters'] for w in pts]);y=np.array([w['k_star'] for w in pts])+math.log2(1e-3)
        b,a=np.polyfit(x,y,1);fits[arm]={'a':float(a),'b':float(b),'points':len(pts),'residual_log2':[float(v) for v in y-(a+b*x)]}
    horizon={}
    for arm in HORIZON_ARMS:
        h1=[w for w in widths if w['arm']==arm and w['horizon']==1 and w['d_model']==LADDER[arm][0]]
        h4=[w for w in widths if w['arm']==arm and w['horizon']==4]
        if h1 and h4:horizon[arm]=(h4[0]['k_star']-h1[0]['k_star'])/math.log2(h4[0]['steps']/h1[0]['steps'])
    shared=None;arms=[a for a in fits]
    if len(arms)>=2:
        rows=[(arms.index(w['arm']),math.log2(w['non_embedding_parameters']),w['k_star']+math.log2(1e-3)) for w in widths if w['horizon']==1 and w['arm'] in arms]
        X=np.zeros((len(rows),len(arms)+1));Y=np.array([r[2] for r in rows])
        for i,(j,x,_) in enumerate(rows):X[i,j]=1;X[i,-1]=x
        coef=np.linalg.lstsq(X,Y,rcond=None)[0];shared={'b':float(coef[-1]),'a':{a:float(coef[i]) for i,a in enumerate(arms)}}
    sweep_steps=next((w['steps'] for w in widths if w['horizon']==1),None);predictions={}
    for name,(arm,tokens) in TARGETS.items():
        if arm not in fits or HORIZON_SOURCE[arm] not in horizon:continue
        steps=round(tokens/TOKENS_PER_STEP);c=horizon[HORIZON_SOURCE[arm]];shift=c*math.log2(steps/sweep_steps);x=math.log2(N_500[arm])
        own=fits[arm]['a']+fits[arm]['b']*x+shift
        pred={'arm':arm,'tokens':tokens,'steps':steps,'horizon_exponent':c,'lr':2**own,'lr_at_sweep_length':2**(own-shift)}
        if shared:pred['lr_shared_slope']=2**(shared['a'][arm]+shared['b']*x+shift)
        predictions[name]=pred
    out={'widths':widths,'fits':fits,'horizon_exponents':horizon,'shared_slope_fit':shared,'predictions':predictions,'sweep_steps':sweep_steps}
    RESULTS.mkdir(parents=True,exist_ok=True);(RESULTS/'lr_sweep.json').write_text(json.dumps(out,indent=2)+'\n')
    lines=['# Learning-rate scaling sweep — results','','Generated by `scripts/summarize_lr_sweep.py`; the protocol is in [LR_SCALING.md](../../LR_SCALING.md).','',
           '## Optimum per width','','| Arm | d | Tokens | Non-embedding | Held-out loss by learning rate | Best grid lr | lr* |','|---|---:|---:|---:|---|---:|---:|']
    for w in widths:
        losses=', '.join(f'{k}: {"diverged" if v is None else f"{v:.4f}"}' for k,v in sorted(w['losses'].items(),key=lambda kv:float(kv[0])))
        lines.append(f"| {w['arm']} | {w['d_model']} | {w['steps']*TOKENS_PER_STEP/1e6:.0f}M | {w['non_embedding_parameters']/1e6:.1f}M | {losses} | {w['best_lr']:.2e} | {w['lr_star']:.2e} |")
    lines+=['','## Fits','','| Arm | Slope b (log2 lr* per doubling of N) | Residuals (log2) | Training-length exponent c (per doubling of steps) |','|---|---:|---|---:|']
    for arm,f in fits.items():
        c=horizon.get(HORIZON_SOURCE[arm]);lines.append(f"| {arm} | {f['b']:.3f} | {', '.join(f'{r:+.2f}' for r in f['residual_log2'])} | {'' if c is None else f'{c:.3f}'} ({HORIZON_SOURCE[arm]}) |")
    if shared:lines+=['',f"Shared-slope fit: b = {shared['b']:.3f}."]
    lines+=['','## Predicted learning rates for the 500M runs','','| Run | Tokens | Steps | Per-arm fit | Shared-slope fit | Per-arm fit at the sweep length |','|---|---:|---:|---:|---:|---:|']
    for name,p in predictions.items():
        lines.append(f"| {name} | {p['tokens']/1e9:.0f}B | {p['steps']} | **{p['lr']:.2e}** | {p.get('lr_shared_slope',float('nan')):.2e} | {p['lr_at_sweep_length']:.2e} |")
    (RESULTS/'LR_SWEEP.md').write_text('\n'.join(lines)+'\n');print('\n'.join(lines))

if __name__=='__main__':main()
