"""Summarize the CTM-augmented RDT screen (research/CTM_RDT_SCREEN.md).

For each mechanism and seed, the paired difference in held-out loss against
the RDT with the same seed (same data order and same initialization of the
shared parameters) and the training throughput relative to the RDT. Decision
rule, fixed before the runs: a mechanism advances if it lowers the held-out
loss on both seeds and by at least 0.01 nats on average; at most the two best
advance to a confirmation.
"""
import json
from pathlib import Path
from scripts.lr_sweep import RUNS,SCREEN_SEEDS,SCREEN_VARIANTS,SCREEN_WIDTH,outcome,plan,run_name

THRESHOLD=0.01;MAX_ADVANCE=2;OUT=Path('research/results/ctm_rdt_screen')


def throughput(name):
    """Training tokens per second after compilation (steps 6 onward), excluding steps that ran an evaluation."""
    rows=[json.loads(r) for r in (RUNS/name/'metrics.jsonl').read_text().splitlines() if r.strip()]
    rows=[r for r in rows[5:] if 'validation' not in r]
    return sum(r['tokens_per_second']*r['seconds'] for r in rows)/sum(r['seconds'] for r in rows)


def main():
    want=plan()[0];base='rdt_aware'
    k=next((r[2] for r in want if r[0]==SCREEN_VARIANTS[1] and r[1]==SCREEN_WIDTH),None)  # the screen's grid point
    runs={(r[0],r[4]):r for r in want if r[0] in SCREEN_VARIANTS and r[1:4]==(SCREEN_WIDTH,k,1) and r[4] in SCREEN_SEEDS}
    if k is None or len(runs)<len(SCREEN_VARIANTS)*len(SCREEN_SEEDS) or any(outcome(run_name(*r))[0] not in ('complete','diverged','collapsed') for r in runs.values()):
        print('screen incomplete');return
    loss={key:outcome(run_name(*r))[1] for key,r in runs.items()}
    speed={key:throughput(run_name(*r)) for key,r in runs.items() if outcome(run_name(*r))[0]=='complete'}
    rows=[]
    for v in SCREEN_VARIANTS[1:]:
        diffs=[loss[(v,s)]-loss[(base,s)] for s in SCREEN_SEEDS];mean=sum(diffs)/len(diffs)
        rel=[speed[(v,s)]/speed[(base,s)] for s in SCREEN_SEEDS if (v,s) in speed and (base,s) in speed]
        rows.append({'mechanism':v.split('+',1)[1],'loss':{s:loss[(v,s)] for s in SCREEN_SEEDS},'paired_difference':diffs,'mean_difference':mean,
                     'relative_throughput':sum(rel)/len(rel) if rel else None,'qualifies':all(d<0 for d in diffs) and mean<=-THRESHOLD})
    ranked=sorted((r for r in rows if r['qualifies']),key=lambda r:r['mean_difference'])
    for r in rows:r['advances']=r in ranked[:MAX_ADVANCE]
    out={'width':SCREEN_WIDTH,'lr':1e-3*2**k,'seeds':list(SCREEN_SEEDS),'rdt_loss':{s:loss[(base,s)] for s in SCREEN_SEEDS},'mechanisms':rows,
         'rule':f'advance if lower on every seed and mean paired difference <= -{THRESHOLD}; at most {MAX_ADVANCE}'}
    OUT.mkdir(parents=True,exist_ok=True);(OUT/'screen.json').write_text(json.dumps(out,indent=2)+'\n')
    lines=['# CTM-augmented RDT screen — results','',f'Generated by `scripts/summarize_ctm_rdt_screen.py`; the protocol is in [CTM_RDT_SCREEN.md](../../CTM_RDT_SCREEN.md).','',
           f"Compute-aware RDT at d {SCREEN_WIDTH}, 100M tokens, learning rate {out['lr']:.2e}. RDT held-out loss: "+', '.join(f'seed {s}: {v:.4f}' for s,v in out['rdt_loss'].items())+'.','',
           '| Mechanism | Held-out loss by seed | Paired difference vs RDT | Mean | Throughput vs RDT | Advances |','|---|---|---|---:|---:|---|']
    for r in rows:
        speed_text='' if r['relative_throughput'] is None else f"{r['relative_throughput']:.2f}×"
        lines.append(f"| {r['mechanism']} | {', '.join(f'{v:.4f}' for v in r['loss'].values())} | {', '.join(f'{d:+.4f}' for d in r['paired_difference'])} | {r['mean_difference']:+.4f} | "
                     f"{speed_text} | {'**yes**' if r['advances'] else 'no'} |")
    lines+=['',f"Rule: {out['rule']}."]
    (OUT/'SCREEN.md').write_text('\n'.join(lines)+'\n');print('\n'.join(lines))

if __name__=='__main__':main()
